=== shawnphoffman/star-wars-codex-data/schema/collection.schema.json
{
  "$id": "https://star-wars-codex-data/schema/collection.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "canonStatus": {
      "enum": [
        "canon",
        "non-canon",
        "other"
      ],
      "type": "string"
    },
    "collectionType": {
      "enum": [
        "tradePaperback",
        "omnibus",
        "hardcover",
        "treasuryEdition",
        "other"
      ],
      "type": "string"
    },
    "collects": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "displayTitle": {
      "minLength": 1,
      "type": "string"
    },
    "era": {
      "type": "string"
    },
    "releaseDate": {
      "type": "string"
    },
    "slug": {
      "minLength": 1,
      "type": "string"
    },
    "synopsis": {
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    }
  },
  "required": [
    "slug",
    "title",
    "displayTitle",
    "collectionType",
    "canonStatus"
  ],
  "title": "Collection",
  "type": "object"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_doctor-aphra-vol-6-ascendant_651.json
{
  "canonStatus": "canon",
  "collectionType": "tradePaperback",
  "collects": [
    "doctor-aphra-2020-01",
    "doctor-aphra-2020-26",
    "doctor-aphra-2020-28",
    "doctor-aphra-2020-29",
    "doctor-aphra-2020-30",
    "doctor-aphra-2020-31"
  ],
  "displayTitle": "Doctor Aphra Vol. 6: Ascendant",
  "slug": "c_doctor-aphra-vol-6-ascendant_651",
  "title": "Doctor Aphra Vol. 6: Ascendant"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_dark-empire-ii-2nd-edition_903.json
{
  "canonStatus": "non-canon",
  "collectionType": "tradePaperback",
  "collects": [
    "dark-empire-ii-1994-1",
    "dark-empire-ii-1994-2",
    "dark-empire-ii-1994-3",
    "dark-empire-ii-1994-4",
    "dark-empire-ii-1994-5",
    "dark-empire-ii-1994-6",
    "empire-s-end-1995-1",
    "empire-s-end-2-rage-of-the-emperor"
  ],
  "displayTitle": "Dark Empire II 2nd Edition",
  "slug": "c_dark-empire-ii-2nd-edition_903",
  "title": "Dark Empire II 2nd Edition"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_obi-wan-a-jedi-s-purpose_106.json
{
  "canonStatus": "canon",
  "collectionType": "tradePaperback",
  "collects": [
    "obi-wan-1",
    "obi-wan-2",
    "obi-wan-3",
    "obi-wan-4",
    "obi-wan-5"
  ],
  "displayTitle": "Obi-Wan: A Jedi's Purpose",
  "era": "reignOfTheEmpire",
  "releaseDate": "2022-12-13T00:00:00.000Z",
  "slug": "c_obi-wan-a-jedi-s-purpose_106",
  "synopsis": "Fast approaches the ultimate destiny of one of the Jedi’s most renowned masters! As he spends his final days in the remote deserts of Tatooine, Obi-Wan Kenobi takes time to reflect on – and record – key moments of a heroic life long-lived. Writing in old leather-bound journals from his hermit’s hut, Obi-Wan remembers his days as a young Jedi Initiate, his trials as a Padawan, the crucible of Jedi Knighthood and the Clone Wars, and some of the earliest challenges he faced as a true Master of the Force! In this tale, Obi-Wan considers a watershed Youngling adventure he narrowly survived on Coruscant when he was but eight years of age…This is just the beginning of his Jedi journey!",
  "title": "Obi-Wan: A Jedi's Purpose"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_classic-star-wars-volume-1-in-deadly-pursuit_224.json
{
  "canonStatus": "non-canon",
  "collectionType": "tradePaperback",
  "collects": [
    "classic-star-wars-02-darth-vader-strikes",
    "classic-star-wars-03-darth-vader-strikes-pt-2",
    "classic-star-wars-07-traitor-s-gambit",
    "classic-star-wars-09-the-night-beast-pt-2",
    "classic-star-wars-10-the-return-of-ben-kenobi",
    "classic-star-wars-13-revenge-of-the-jedi",
    "classic-star-wars-14-doom-mission",
    "classic-star-wars-17-the-paradise-detour",
    "classic-star-wars-18-a-new-beginning",
    "classic-star-wars-19-a-new-beginning-pt-2"
  ],
  "displayTitle": "Classic Star Wars Volume 1: In Deadly Pursuit",
  "releaseDate": "1994-06-01T00:00:00.000Z",
  "slug": "c_classic-star-wars-volume-1-in-deadly-pursuit_224",
  "title": "Classic Star Wars Volume 1: In Deadly Pursuit"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_darth-vader-and-the-cry-of-shadows_833.json
{
  "canonStatus": "non-canon",
  "collectionType": "hardcover",
  "collects": [
    "darth-vader-and-the-cry-of-shadows-1",
    "darth-vader-and-the-cry-of-shadows-2",
    "darth-vader-and-the-cry-of-shadows-3",
    "darth-vader-and-the-cry-of-shadows-4",
    "darth-vader-and-the-cry-of-shadows-5"
  ],
  "displayTitle": "Darth Vader and the Cry of Shadows",
  "slug": "c_darth-vader-and-the-cry-of-shadows_833",
  "title": "Darth Vader and the Cry of Shadows"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_star-wars-legends-epic-collection-the-empire-vol-5_716.json
{
  "canonStatus": "non-canon",
  "collectionType": "omnibus",
  "collects": [
    "galaxy-of-fear-1997-1",
    "star-wars-droids-1-the-destroyer",
    "star-wars-droids-2-the-ultimate-weapon",
    "star-wars-droids-3-the-scarlet-pirate",
    "star-wars-droids-4-lost-in-time",
    "star-wars-droids-5-separated",
    "star-wars-droids-6-star-wars-according-to-the-droids-book",
    "star-wars-droids-7-star-wars-according-to-the-droids-book-ii",
    "star-wars-droids-8-star-wars-according-to-the-droids-book-iii"
  ],
  "displayTitle": "Legends Epic Collection: The Empire Vol. 5",
  "slug": "c_star-wars-legends-epic-collection-the-empire-vol-5_716",
  "synopsis": "Collects Star Wars: Droids (1994) Special and #1-6 (AKA The Kalarba Adventures #1-6); material from Star Wars Galaxy Magazine #1 (between Kalarba 5-6); Star Wars: Droids (1995) #1-8 (“Rebellion” and “Season of Revolt”); Droids: The Protocol Offensive OGN; and material from Star Wars Tales #16 & 20.",
  "title": "Star Wars Legends Epic Collection: The Empire Vol. 5"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_legends-epic-collection-the-old-republic-vol-5_331.json
{
  "canonStatus": "non-canon",
  "collectionType": "tradePaperback",
  "collects": [
    "jedi-vs-sith-1",
    "jedi-vs-sith-2",
    "jedi-vs-sith-3",
    "jedi-vs-sith-4",
    "jedi-vs-sith-5",
    "jedi-vs-sith-6",
    "knight-errant-aflame-2010-1",
    "knight-errant-aflame-2010-2",
    "knight-errant-aflame-2010-3",
    "knight-errant-aflame-2010-4",
    "knight-errant-aflame-2010-5",
    "knight-errant-deluge-2011-1",
    "knight-errant-deluge-2011-2",
    "knight-errant-deluge-2011-3",
    "knight-errant-deluge-2011-4",
    "knight-errant-deluge-2011-5",
    "knight-errant-escape-2012-1",
    "knight-errant-escape-2012-2",
    "knight-errant-escape-2012-3",
    "knight-errant-escape-2012-4",
    "knight-errant-escape-2012-5"
  ],
  "displayTitle": "Legends Epic Collection: The Old Republic Vol. 5",
  "releaseDate": "2023-03-14T00:00:00.000Z",
  "slug": "c_legends-epic-collection-the-old-republic-vol-5_331",
  "title": "Legends Epic Collection: The Old Republic Vol. 5"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_star-wars-legends-epic-collection-the-new-republic-vol-2_737.json
{
  "canonStatus": "non-canon",
  "collectionType": "omnibus",
  "collects": [
    "the-rebel-opposition-1",
    "the-rebel-opposition-2",
    "the-rebel-opposition-3",
    "the-rebel-opposition-4",
    "x-wing-rogue-leader-2005-1",
    "x-wing-rogue-leader-2005-2",
    "x-wing-rogue-leader-2005-3",
    "x-wing-rogue-squadron-05-the-phantom-affair-part-1",
    "x-wing-rogue-squadron-06-the-phantom-affair-part-2",
    "x-wing-rogue-squadron-07-the-phantom-affair-part-3",
    "x-wing-rogue-squadron-08-the-phantom-affair-part-4",
    "x-wing-rogue-squadron-10-battleground-tatooine-part-2",
    "x-wing-rogue-squadron-11-battleground-tatooine-part-3",
    "x-wing-rogue-squadron-12-battleground-tatooine-part-4",
    "x-wing-rogue-squadron-13-the-warrior-princess-part-1",
    "x-wing-rogue-squadron-14-the-warrior-princess-part-2",
    "x-wing-rogue-squadron-15-the-warrior-princess-part-3",
    "x-wing-rogue-squadron-16-the-warrior-princess-part-4",
    "x-wing-rogue-squadron-9-battleground-tatooine-part-1"
  ],
  "displayTitle": "Legends Epic Collection: The New Republic Vol. 2",
  "slug": "c_star-wars-legends-epic-collection-the-new-republic-vol-2_737",
  "synopsis": "Collects Star Wars: X-Wing Rogue Leader #1-3; Star Wars: X-Wing Rogue Squadron #1-16 & Special; and material from Star Wars Tales #12 & 23",
  "title": "Star Wars Legends Epic Collection: The New Republic Vol. 2"
}
