=== shawnphoffman/star-wars-codex-data/schema/collection.schema.json
{
  "$id": "https://star-wars-codex-data/schema/collection.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "canonStatus": {
      "enum": [
        "canon",
        "non-canon",
        "other"
      ],
      "type": "string"
    },
    "collectionType": {
      "enum": [
        "tradePaperback",
        "omnibus",
        "hardcover",
        "treasuryEdition",
        "other"
      ],
      "type": "string"
    },
    "collects": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "displayTitle": {
      "minLength": 1,
      "type": "string"
    },
    "era": {
      "type": "string"
    },
    "releaseDate": {
      "type": "string"
    },
    "slug": {
      "minLength": 1,
      "type": "string"
    },
    "synopsis": {
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    }
  },
  "required": [
    "slug",
    "title",
    "displayTitle",
    "collectionType",
    "canonStatus"
  ],
  "title": "Collection",
  "type": "object"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_omnibus-shadows-of-the-empire_379.json
{
  "canonStatus": "non-canon",
  "collectionType": "omnibus",
  "collects": [
    "mara-jade-by-the-emperor-s-hand-1998-0",
    "mara-jade-by-the-emperor-s-hand-1998-1",
    "mara-jade-by-the-emperor-s-hand-1998-3",
    "mara-jade-by-the-emperor-s-hand-1998-4",
    "mara-jade-by-the-emperor-s-hand-1998-5",
    "mara-jade-by-the-emperor-s-hand-1998-6",
    "mara-jade-by-the-emperor-s-hand-2",
    "shadows-of-the-empire-1",
    "shadows-of-the-empire-2",
    "shadows-of-the-empire-3",
    "shadows-of-the-empire-4",
    "shadows-of-the-empire-5",
    "shadows-of-the-empire-6",
    "shadows-of-the-empire-evolution-1998-1",
    "shadows-of-the-empire-evolution-1998-2",
    "shadows-of-the-empire-evolution-1998-3",
    "shadows-of-the-empire-evolution-1998-4",
    "shadows-of-the-empire-evolution-1998-5"
  ],
  "displayTitle": "Omnibus: Shadows of the Empire",
  "releaseDate": "2010-01-27T00:00:00.000Z",
  "slug": "c_omnibus-shadows-of-the-empire_379",
  "title": "Omnibus: Shadows of the Empire"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_legends-epic-collection-tales-of-the-jedi-vol-1_298.json
{
  "canonStatus": "non-canon",
  "collectionType": "tradePaperback",
  "collects": [
    "tales-of-the-jedi-1-ulic-qel-droma-and-the-beast-wars-of-onderon-part-1"
  ],
  "displayTitle": "Legends Epic Collection: Tales of the Jedi Vol. 1",
  "releaseDate": "2020-12-08T00:00:00.000Z",
  "slug": "c_legends-epic-collection-tales-of-the-jedi-vol-1_298",
  "title": "Legends Epic Collection: Tales of the Jedi Vol. 1"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_tales-from-the-nightlands_162.json
{
  "canonStatus": "canon",
  "collectionType": "tradePaperback",
  "collects": [
    "star-wars-tales-from-the-nightlands-1",
    "star-wars-tales-from-the-nightlands-2",
    "star-wars-tales-from-the-nightlands-3"
  ],
  "displayTitle": "Tales From the Nightlands",
  "releaseDate": "2026-03-17T00:00:00.000Z",
  "slug": "c_tales-from-the-nightlands_162",
  "synopsis": "Tales From the Nightlands is a collection of all 3 issues from the Nightlands mini series\nCavan Scott, Star Wars master of the macabre, conjures an all-new Halloween special from a galaxy far, far away in this original graphic novel. Contained herein is a trio of terrifying tales that span the Skywalker saga!\nOn the planet Ryloth, Twi’leks speak in hushed tones about the Nightlands, the spectral realm where their spirits retire after death. According to legend, there are certain nights when the veil between that haunted place and the land of the living is so thin that one can communicate with the other side.\nIt was on one such night that young Padawan Anakin Skywalker, while visiting Ryloth with Master Obi-Wan Kenobi, attempted to summon the ghost of Qui-Gon Jinn for a final goodbye. But when Anakin made contact with the Nightlands, it wasn’t his old friend who answered…\nEnter: The Nightlander, a Star Wars boogeyman who seeks to possess a powerful, living host and bring despair to the galaxy!\nIn this terrifying new tale, three generations of galactic heroes contend with the malevolent Nightlander, else it escapes its frightful dimension to torment the waking world. Watch in horror as Anakin, Luke, Leia, and Rey face off against a dark power unlike any in the galaxy!\nCollecting: Tales From the Nightlands #1-3",
  "title": "Tales From the Nightlands"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_star-wars-jango-fett_666.json
{
  "canonStatus": "canon",
  "collectionType": "tradePaperback",
  "collects": [
    "revelations-1"
  ],
  "displayTitle": "Jango Fett",
  "slug": "c_star-wars-jango-fett_666",
  "synopsis": "collects a story from Star Wars: Revelations (2023) #1. This series is actually set slightly prior to the prequels, since it deals with a pre-cloning Jango Fett.",
  "title": "Star Wars: Jango Fett"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_legends-epic-collection-the-clone-wars-vol-2_302.json
{
  "canonStatus": "non-canon",
  "collectionType": "tradePaperback",
  "collects": [
    "darth-maul-death-sentence-2012-1",
    "darth-maul-death-sentence-2012-2",
    "darth-maul-death-sentence-2012-3",
    "darth-maul-death-sentence-2012-4",
    "republic-1999-56",
    "republic-1999-61",
    "republic-1999-64",
    "republic-1999-66",
    "republic-55-the-battle-of-jabiim-part-1",
    "republic-57-the-battle-of-jabiim-part-3",
    "republic-58-the-battle-of-jabiim-part-4",
    "republic-59-enemy-lines",
    "republic-60-hate-and-fear",
    "republic-62-no-man-s-land",
    "republic-63-striking-from-the-shadows",
    "republic-65-show-of-force-part-1",
    "republic-67-forever-young"
  ],
  "displayTitle": "Legends Epic Collection: The Clone Wars Vol. 2",
  "releaseDate": "2018-04-03T00:00:00.000Z",
  "slug": "c_legends-epic-collection-the-clone-wars-vol-2_302",
  "title": "Legends Epic Collection: The Clone Wars Vol. 2"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_dark-times-volume-7-a-spark-remains_251.json
{
  "canonStatus": "non-canon",
  "collectionType": "tradePaperback",
  "collects": [
    "dark-times-28-a-spark-remains-1",
    "dark-times-29-a-spark-remains-2",
    "dark-times-30-a-spark-remains-3",
    "dark-times-31-a-spark-remains-4",
    "dark-times-32-a-spark-remains-5"
  ],
  "displayTitle": "Dark Times Volume 7: A Spark Remains",
  "releaseDate": "2013-11-18T00:00:00.000Z",
  "slug": "c_dark-times-volume-7-a-spark-remains_251",
  "title": "Dark Times Volume 7: A Spark Remains"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_legends-epic-collection-the-empire-vol-2_306.json
{
  "canonStatus": "non-canon",
  "collectionType": "tradePaperback",
  "collects": [
    "dark-times-06-parallels-part-1",
    "dark-times-07-parallels-part-2",
    "dark-times-08-parallels-part-3",
    "dark-times-09-parallels-part-4",
    "dark-times-10-parallels-part-5",
    "dark-times-11-vector-part-5",
    "dark-times-12-vector-part-6",
    "dark-times-13-blue-harvest-part-1",
    "dark-times-14-blue-harvest-part-2",
    "dark-times-15-blue-harvest-part-3",
    "dark-times-16-blue-harvest-part-4",
    "dark-times-17-blue-harvest-part-5",
    "dark-times-18-out-of-the-wilderness-1",
    "dark-times-19-out-of-the-wilderness-2",
    "dark-times-20-out-of-the-wilderness-3",
    "dark-times-21-out-of-the-wilderness-4",
    "dark-times-22-out-of-the-wilderness-5"
  ],
  "displayTitle": "Legends Epic Collection: The Empire Vol. 2",
  "releaseDate": "2015-11-03T00:00:00.000Z",
  "slug": "c_legends-epic-collection-the-empire-vol-2_306",
  "title": "Legends Epic Collection: The Empire Vol. 2"
}

=== shawnphoffman/star-wars-codex-data/data/collections/c_star-wars-crimson-reign_668.json
{
  "canonStatus": "canon",
  "collectionType": "hardcover",
  "collects": [
    "bounty-hunters-18",
    "bounty-hunters-19",
    "bounty-hunters-20",
    "bounty-hunters-21",
    "bounty-hunters-22",
    "bounty-hunters-23",
    "bounty-hunters-24",
    "crimson-reign-1",
    "crimson-reign-2",
    "crimson-reign-3",
    "crimson-reign-4",
    "crimson-reign-5"
  ],
  "displayTitle": "Crimson Reign",
  "slug": "c_star-wars-crimson-reign_668",
  "synopsis": "collects Star Wars: Crimson Reign (2021) #1-5, Star Wars (2020) #19-25, Star Wars: Bounty Hunters (2020) #18-24, Star Wars: Darth Vader (2020) #18-24, and Star Wars: Doctor Aphra (2020) #16-21.",
  "title": "Star Wars: Crimson Reign"
}
