=== shawnphoffman/star-wars-codex-data/schema/work.schema.json
{
  "$id": "https://star-wars-codex-data/schema/work.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "bookType": {
      "type": "string"
    },
    "canonStatus": {
      "enum": [
        "canon",
        "non-canon",
        "other"
      ],
      "type": "string"
    },
    "creators": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "name": {
            "minLength": 1,
            "type": "string"
          },
          "role": {
            "type": "string"
          },
          "slug": {
            "type": "string"
          }
        },
        "required": [
          "name"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "displayTitle": {
      "minLength": 1,
      "type": "string"
    },
    "editionIds": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "type": {
            "enum": [
              "isbn13",
              "isbn10",
              "asin",
              "audibleAsin",
              "upc",
              "diamondCode"
            ],
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        },
        "required": [
          "type",
          "value"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "editions": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "asin": {
            "type": "string"
          },
          "audibleAsin": {
            "type": "string"
          },
          "extent": {
            "type": "number"
          },
          "imprint": {
            "type": "string"
          },
          "isPrimary": {
            "type": "boolean"
          },
          "isbn10": {
            "type": "string"
          },
          "isbn13": {
            "type": "string"
          },
          "kind": {
            "enum": [
              "print",
              "ebook",
              "audio"
            ],
            "type": "string"
          },
          "onsale": {
            "type": "string"
          },
          "upc": {
            "type": "string"
          }
        },
        "required": [
          "kind"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "era": {
      "type": "string"
    },
    "format": {
      "type": "string"
    },
    "inUniverseDate": {
      "additionalProperties": false,
      "properties": {
        "endYear": {
          "type": "integer"
        },
        "startYear": {
          "type": "integer"
        }
      },
      "type": "object"
    },
    "movie": {
      "additionalProperties": false,
      "properties": {
        "movieType": {
          "type": "string"
        },
        "mpaaRating": {
          "type": "string"
        },
        "runtimeMinutes": {
          "type": "number"
        },
        "subtitle": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "parentWorkSlug": {
      "type": "string"
    },
    "periodical": {
      "additionalProperties": false,
      "properties": {
        "imprint": {
          "type": "string"
        },
        "pageCount": {
          "type": "number"
        },
        "publicationKind": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "relatedWorkSlugs": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "releaseDate": {
      "type": "string"
    },
    "releaseDisplayState": {
      "type": "string"
    },
    "releaseStatus": {
      "type": "string"
    },
    "slug": {
      "minLength": 1,
      "type": "string"
    },
    "synopsis": {
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    }
  },
  "required": [
    "slug",
    "title",
    "displayTitle",
    "format",
    "canonStatus",
    "releaseDisplayState"
  ],
  "title": "Work",
  "type": "object"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/darth-vader-2020-06.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Greg Pak",
      "role": "writer",
      "slug": "greg-pak"
    },
    {
      "name": "Raffaele Ienco",
      "role": "artist",
      "slug": "raffaele-ienco"
    }
  ],
  "displayTitle": "Darth Vader (2020) #06",
  "era": "ageOfRebellion",
  "format": "periodicalIssue",
  "inUniverseDate": {
    "startYear": 3
  },
  "parentWorkSlug": "darth-vader-2020",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2020-10-14T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "darth-vader-2020-06",
  "synopsis": "Darth Vader (2020) #6 is the sixth issue of the canon comic series Star Wars: Darth Vader (2020).\nDARTH VADER failed to turn his son, Luke Skywalker, to the dark side of the Force.\nNo…Luke was too weak to join his father in overthrowing EMPEROR PALPATINE.\nVader sought revenge against those who hid Luke from him for all of these years…\nand in doing so nearly betrayed his master. It did not go unnoticed by Palpatine… time for Vader's next lesson",
  "title": "Darth Vader (2020) #06"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/darth-vader-and-the-ghost-prison-2.json
{
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "W. Haden Blackman",
      "role": "writer",
      "slug": "w-haden-blackman"
    }
  ],
  "displayTitle": "Darth Vader and the Ghost Prison #2",
  "era": "fallOfTheJedi",
  "format": "periodicalIssue",
  "inUniverseDate": {
    "startYear": -19
  },
  "parentWorkSlug": "darth-vader-and-the-ghost-prison-graphic-novel",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2012-06-20T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "darth-vader-and-the-ghost-prison-2",
  "synopsis": "Graduating cadet Tohm's first night as an Imperial officer has already seen him assisting Darth Vader in fighting a traitorous uprising, saving Emperor Palpatine from a deadly plague weapon, and keeping the peace between Vader and the cybernetic Moff Trachta. Now Tohm and Vader have infiltrated the deathly stillness of the abandoned Jedi Temple to confront the secrets of Vader's past, and to learn the facts about the Ghost Prison!",
  "title": "Darth Vader and the Ghost Prison #2"
}

=== shawnphoffman/star-wars-codex-data/data/works/tv-episode/young-jedi-adventures-s2e41.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Casey Lowe",
      "role": "director",
      "slug": "casey-lowe"
    },
    {
      "name": "Christian Streaty",
      "role": "writer",
      "slug": "christian-streaty"
    }
  ],
  "displayTitle": "Fossil Hunt",
  "era": "highRepublic",
  "format": "tvEpisode",
  "parentWorkSlug": "young-jedi-adventures-s2",
  "releaseDate": "2025-05-09T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "young-jedi-adventures-s2e41",
  "synopsis": "\"Fossil Hunt\" is the second part of the twenty-first episode of the second season the animated series Star Wars: Young Jedi Adventures. It was released on Disney+ on March 19, 2025.",
  "title": "Fossil Hunt"
}

=== shawnphoffman/star-wars-codex-data/data/works/tv-series/disney-gallery-the-mandalorian.json
{
  "canonStatus": "other",
  "creators": [
    {
      "name": "Jon Favreau",
      "role": "producer",
      "slug": "jon-favreau"
    },
    {
      "name": "Kathleen Kennedy",
      "role": "producer",
      "slug": "kathleen-kennedy"
    },
    {
      "name": "Dave Filoni",
      "role": "producer",
      "slug": "dave-filoni"
    },
    {
      "name": "Bradford Baruh",
      "role": "producer",
      "slug": "bradford-baruh"
    },
    {
      "name": "Karen Gilchrist",
      "role": "producer",
      "slug": "karen-gilchrist"
    },
    {
      "name": "John Bartnicki",
      "role": "producer",
      "slug": "john-bartnicki"
    },
    {
      "name": "Michael Kramer",
      "role": "composer",
      "slug": "michael-kramer"
    }
  ],
  "displayTitle": "Disney Gallery: The Mandalorian",
  "format": "tvSeries",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2020-05-04T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "disney-gallery-the-mandalorian",
  "title": "Disney Gallery: The Mandalorian"
}

=== shawnphoffman/star-wars-codex-data/data/works/tv-episode/star-wars-droids-tv-series-season-1-s01-star-wars-droids-tv-series-s01e10.json
{
  "canonStatus": "non-canon",
  "displayTitle": "Tail of the Roon Comets",
  "format": "tvEpisode",
  "parentWorkSlug": "star-wars-droids-tv-series-season-1-s01",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "1985-11-09T00:00:00.000Z",
  "releaseDisplayState": "upcoming",
  "slug": "star-wars-droids-tv-series-season-1-s01-star-wars-droids-tv-series-s01e10",
  "synopsis": "R2-D2, C-3PO and Mungo Baobab are captured by the Empire on the way to the Roon system.",
  "title": "Tail of the Roon Comets"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/jabba-the-hutt-the-garr-suppoon-hit.json
{
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "Jim Woodring",
      "role": "writer",
      "slug": "jim-woodring"
    },
    {
      "name": "Art Wetherell",
      "role": "penciler",
      "slug": "art-wetherell"
    },
    {
      "name": "Monty Sheldon",
      "role": "inker",
      "slug": "monty-sheldon"
    },
    {
      "name": "James Sinclair",
      "role": "colorist",
      "slug": "james-sinclair"
    },
    {
      "name": "Steve Dutro",
      "role": "letterer",
      "slug": "steve-dutro"
    },
    {
      "name": "Ryder Windham",
      "role": "editor",
      "slug": "ryder-windham"
    },
    {
      "name": "Scott Tice",
      "slug": "scott-tice"
    },
    {
      "name": "Steve Bissette",
      "role": "coverArtist",
      "slug": "steve-bissette"
    },
    {
      "name": "Cam Kennedy",
      "role": "coverArtist",
      "slug": "cam-kennedy"
    }
  ],
  "displayTitle": "Jabba the Hutt: The Garr Suppoon Hit",
  "format": "periodicalIssue",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "1995-04-01T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "jabba-the-hutt-the-garr-suppoon-hit",
  "synopsis": "Jabba the Hutt lives to negotiate, and the art of the deal is his only discipline. But the goods he trades are the lives of others, and in that line of business you can't lose your head. In this self-contained story, Jabba finds himself bartering with Garr Suppoon, rumored to be an absolute devil at the negotiating table. There's a valuable lesson to be learned here: In a deal with the devil, you can always refuse. In a deal with Jabba, it's not advised.",
  "title": "Jabba the Hutt: The Garr Suppoon Hit"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/star-wars-insider-insider-188.json
{
  "canonStatus": "canon",
  "displayTitle": "Insider #188",
  "format": "periodicalIssue",
  "parentWorkSlug": "star-wars-insider",
  "periodical": {
    "publicationKind": "magazine",
    "type": "singleIssue"
  },
  "releaseDisplayState": "announced",
  "slug": "star-wars-insider-insider-188",
  "title": "Insider #188"
}

=== shawnphoffman/star-wars-codex-data/data/works/book/return-of-the-jedi-the-special-edition.json
{
  "bookType": "graphicNovel",
  "canonStatus": "canon",
  "displayTitle": "Return of the Jedi: The Special Edition",
  "format": "book",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDisplayState": "announced",
  "slug": "return-of-the-jedi-the-special-edition",
  "synopsis": "The trilogy aimed to renew the movies in the minds of both the older and the younger audience, and to prepare the way for the upcoming release of Star Wars: Episode I The Phantom Menace.",
  "title": "Return of the Jedi: The Special Edition"
}
