=== shawnphoffman/star-wars-codex-data/schema/work.schema.json
{
  "$id": "https://star-wars-codex-data/schema/work.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "bookType": {
      "type": "string"
    },
    "canonStatus": {
      "enum": [
        "canon",
        "non-canon",
        "other"
      ],
      "type": "string"
    },
    "creators": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "name": {
            "minLength": 1,
            "type": "string"
          },
          "role": {
            "type": "string"
          },
          "slug": {
            "type": "string"
          }
        },
        "required": [
          "name"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "displayTitle": {
      "minLength": 1,
      "type": "string"
    },
    "editionIds": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "type": {
            "enum": [
              "isbn13",
              "isbn10",
              "asin",
              "audibleAsin",
              "upc",
              "diamondCode"
            ],
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        },
        "required": [
          "type",
          "value"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "editions": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "asin": {
            "type": "string"
          },
          "audibleAsin": {
            "type": "string"
          },
          "extent": {
            "type": "number"
          },
          "imprint": {
            "type": "string"
          },
          "isPrimary": {
            "type": "boolean"
          },
          "isbn10": {
            "type": "string"
          },
          "isbn13": {
            "type": "string"
          },
          "kind": {
            "enum": [
              "print",
              "ebook",
              "audio"
            ],
            "type": "string"
          },
          "onsale": {
            "type": "string"
          },
          "upc": {
            "type": "string"
          }
        },
        "required": [
          "kind"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "era": {
      "type": "string"
    },
    "format": {
      "type": "string"
    },
    "inUniverseDate": {
      "additionalProperties": false,
      "properties": {
        "endYear": {
          "type": "integer"
        },
        "startYear": {
          "type": "integer"
        }
      },
      "type": "object"
    },
    "movie": {
      "additionalProperties": false,
      "properties": {
        "movieType": {
          "type": "string"
        },
        "mpaaRating": {
          "type": "string"
        },
        "runtimeMinutes": {
          "type": "number"
        },
        "subtitle": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "parentWorkSlug": {
      "type": "string"
    },
    "periodical": {
      "additionalProperties": false,
      "properties": {
        "imprint": {
          "type": "string"
        },
        "pageCount": {
          "type": "number"
        },
        "publicationKind": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "relatedWorkSlugs": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "releaseDate": {
      "type": "string"
    },
    "releaseDisplayState": {
      "type": "string"
    },
    "releaseStatus": {
      "type": "string"
    },
    "slug": {
      "minLength": 1,
      "type": "string"
    },
    "synopsis": {
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    }
  },
  "required": [
    "slug",
    "title",
    "displayTitle",
    "format",
    "canonStatus",
    "releaseDisplayState"
  ],
  "title": "Work",
  "type": "object"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/galaxy-of-fear-1997-9.json
{
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "John Whitman",
      "role": "writer",
      "slug": "john-whitman"
    }
  ],
  "displayTitle": "Galaxy of Fear #9: Spore",
  "format": "periodicalIssue",
  "inUniverseDate": {
    "startYear": 1
  },
  "parentWorkSlug": "galaxy-of-fear-1997",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "1998-03-09T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "galaxy-of-fear-1997-9",
  "title": "Galaxy of Fear #9: Spore"
}

=== shawnphoffman/star-wars-codex-data/data/works/book/phasma.json
{
  "bookType": "adultNovel",
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Delilah S. Dawson",
      "role": "writer",
      "slug": "delilah-s-dawson"
    },
    {
      "name": "Larry Rostant",
      "role": "coverArtist",
      "slug": "larry-rostant"
    }
  ],
  "displayTitle": "Phasma",
  "editionIds": [
    {
      "type": "isbn10",
      "value": "1524796336"
    },
    {
      "type": "isbn13",
      "value": "9781524796310"
    },
    {
      "type": "isbn13",
      "value": "9781524796334"
    }
  ],
  "editions": [
    {
      "extent": 380,
      "imprint": "Del Rey",
      "isPrimary": false,
      "isbn13": "9781524796310",
      "kind": "print",
      "onsale": "2017-09-01T00:00:00.000Z"
    },
    {
      "extent": 480,
      "imprint": "Random House Worlds",
      "isPrimary": true,
      "isbn10": "1524796336",
      "isbn13": "9781524796334",
      "kind": "print",
      "onsale": "2018-04-24T00:00:00.000Z"
    }
  ],
  "era": "riseOfTheFirstOrder",
  "format": "book",
  "inUniverseDate": {
    "endYear": 34,
    "startYear": 22
  },
  "releaseDate": "2017-09-01T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "phasma",
  "synopsis": "When a First Order ship crash-lands on a remote world, a determined warrior discovers she doesn't just want to help the survivors. She wants to become one of them.",
  "title": "Phasma"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/ghosts-of-vaders-castle-2.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Cavan Scott",
      "role": "writer",
      "slug": "cavan-scott"
    },
    {
      "name": "Francesco Francavilla",
      "role": "artist",
      "slug": "francesco-francavilla"
    },
    {
      "name": "Derek Charm",
      "role": "artist",
      "slug": "derek-charm"
    }
  ],
  "displayTitle": "Ghosts of Vader's Castle #2",
  "era": "ageOfRebellion",
  "format": "periodicalIssue",
  "parentWorkSlug": "ghosts-of-vaders-castle",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2021-09-29T00:00:00.000Z",
  "releaseDisplayState": "upcoming",
  "slug": "ghosts-of-vaders-castle-2",
  "synopsis": "The epic five week event miniseries Star Wars Adventures: Ghosts of Vader's Castle continues!\nIn issue #2, Lina searches for the now missing Milo and Crater and runs into... Jaxxon! He reveals that he, too, has been having nightmares, but of vicious Wookiees bigger than mountains! It seems the GHOSTS OF VADER'S CASTLE are haunting everyone's dreams…",
  "title": "Ghosts of Vader's Castle #2"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/thrawn-alliances-comics-thrawn-alliances-1.json
{
  "canonStatus": "canon",
  "displayTitle": "Thrawn: Alliances #1",
  "era": "ageOfRebellion",
  "format": "periodicalIssue",
  "parentWorkSlug": "thrawn-alliances-comics",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2018-07-24T00:00:00.000Z",
  "releaseDisplayState": "upcoming",
  "slug": "thrawn-alliances-comics-thrawn-alliances-1",
  "synopsis": "Grand Admiral Thrawn and Darth Vader ally against a threat to the Empire in this new novel from bestselling author Timothy Zahn.\n\"I have sensed a disturbance in the Force.\"\nOminous words under any circumstances, but all the more so when uttered by Emperor Palpatine. On Batuu, at the edges of the Unknown Regions, a threat to the Empire is taking root&mdash;its existence little more than a glimmer, its consequences as yet unknowable. But it is troubling enough to the Imperial leader to warrant investigation by his most powerful agents: ruthless enforcer Lord Darth Vader and brilliant strategist Grand Admiral Thrawn. Fierce rivals for the emperor's favor, and outspoken adversaries on Imperial affairs&mdash;including the Death Star project&mdash;the formidable pair seem unlikely partners for such a crucial mission. But the Emperor knows it's not the first time Vader and Thrawn have joined forces. And there's more behind his royal command than either man suspects.\nIn what seems like a lifetime ago, General Anakin Skywalker of the Galactic Republic, and Commander Mitth'raw'nuruodo, officer of the Chiss Ascendancy, crossed paths for the first time. One on a desperate personal quest, the other with motives unknown&hellip;and undisclosed. But facing a gauntlet of dangers on a far-flung world, they forged an uneasy alliance&mdash;neither remotely aware of what their futures held in store.\nNow, thrust together once more, they find themselves bound again for the planet where they once fo",
  "title": "Thrawn: Alliances #1"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/star-wars-adventures-shadow-of-vader-s-castle-2020-1.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Cavan Scott",
      "role": "writer",
      "slug": "cavan-scott"
    },
    {
      "name": "Derek Charm",
      "role": "artist",
      "slug": "derek-charm"
    },
    {
      "name": "Nick Brokenshire",
      "role": "artist",
      "slug": "nick-brokenshire"
    },
    {
      "name": "Nicoletta Baldari",
      "role": "artist",
      "slug": "nicoletta-baldari"
    }
  ],
  "displayTitle": "Adventures: Shadow of Vader's Castle #1",
  "era": "newRepublic",
  "format": "periodicalIssue",
  "inUniverseDate": {
    "startYear": 4
  },
  "parentWorkSlug": "star-wars-adventures-shadow-of-vader-s-castle-2020",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2020-11-04T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "star-wars-adventures-shadow-of-vader-s-castle-2020-1",
  "synopsis": "Continuing the Vader’s Castle series, this single-issue comic proves that even after good conquers evil, Vader’s looming shadow continues to haunt those who dare trespass on his domain long after his death.",
  "title": "Star Wars Adventures: Shadow of Vader's Castle #1"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/age-of-resistance-general-hux-2019-1.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Leonard Kirk",
      "role": "penciler",
      "slug": "leonard-kirk"
    },
    {
      "name": "Cory Hamscher",
      "role": "inker",
      "slug": "cory-hamscher"
    },
    {
      "name": "Mark Paniccia",
      "role": "editor",
      "slug": "mark-paniccia"
    },
    {
      "name": "Guru Efx",
      "role": "colorist",
      "slug": "guru-efx"
    },
    {
      "name": "Tom Taylor",
      "role": "writer",
      "slug": "tom-taylor"
    },
    {
      "name": "Bria Lavorgna",
      "role": "writer",
      "slug": "bria-lavorgna"
    },
    {
      "name": "Vc Travis Lanham",
      "role": "letterer",
      "slug": "vc-travis-lanham"
    },
    {
      "name": "Phil Noto",
      "role": "coverArtist",
      "slug": "phil-noto"
    }
  ],
  "displayTitle": "Age Of Resistance: General Hux (2019) #1",
  "format": "periodicalIssue",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDisplayState": "announced",
  "slug": "age-of-resistance-general-hux-2019-1",
  "title": "Age Of Resistance: General Hux (2019) #1"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/poe-dameron-24.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Charles Soule",
      "role": "writer",
      "slug": "charles-soule"
    },
    {
      "name": "Angel Unzueta",
      "role": "artist",
      "slug": "angel-unzueta"
    },
    {
      "name": "Joe Caramagna",
      "role": "artist",
      "slug": "joe-caramagna"
    },
    {
      "name": "Arif Pianto",
      "role": "artist",
      "slug": "arif-pianto"
    },
    {
      "name": "Phil Noto",
      "role": "artist",
      "slug": "phil-noto"
    },
    {
      "name": "Angel Unzueta Galarza",
      "role": "inker",
      "slug": "angel-unzueta-galarza"
    },
    {
      "name": "Angel Unzueta Galarza",
      "role": "penciler",
      "slug": "angel-unzueta-galarza"
    },
    {
      "name": "Philip J. Noto",
      "role": "coverArtist",
      "slug": "philip-j-noto"
    },
    {
      "name": "Vc Joe Caramagna",
      "role": "letterer",
      "slug": "vc-joe-caramagna"
    },
    {
      "name": "Jordan D. White",
      "role": "editor",
      "slug": "jordan-d-white"
    },
    {
      "name": "Arif Pianto",
      "role": "colorist",
      "slug": "arif-pianto"
    }
  ],
  "displayTitle": "Poe Dameron #24: Legend Found, Part V",
  "era": "riseOfTheFirstOrder",
  "format": "periodicalIssue",
  "inUniverseDate": {
    "startYear": 34
  },
  "parentWorkSlug": "poe-dameron",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2018-02-14T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "poe-dameron-24",
  "synopsis": "Lor San Tekka has been captured…again! And it's up to Black Squadron to save him. Meanwhile, Terex has his own plans in motion…to finally free himself from the grasp of the First Order!",
  "title": "Poe Dameron #24: Legend Found, Part V"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical/the-phantom-menace-25th-anniversary-special-2024.json
{
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Greg Pak",
      "role": "writer",
      "slug": "greg-pak"
    },
    {
      "name": "Will Sliney",
      "role": "artist",
      "slug": "will-sliney"
    }
  ],
  "displayTitle": "The Phantom Menace 25th Anniversary Special",
  "era": "fallOfTheJedi",
  "format": "periodical",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2024-05-01T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "the-phantom-menace-25th-anniversary-special-2024",
  "synopsis": "CELEBRATING THE 25TH ANNIVERSARY OF THE PHANTOM MENACE WITH AN ALL-NEW STORY! Explore the earliest days and secret inner life of ANAKIN SKYWALKER with never-before-seen, revelatory stories set before, after and between the scenes of the classic movie! Featuring the dream of a JEDI, the gift of a TUSKEN RAIDER, the heart of a GUNGAN, the ache of a mother and the horror of a hero!",
  "title": "The Phantom Menace 25th Anniversary Special"
}
