=== shawnphoffman/star-wars-codex-data/schema/work.schema.json
{
  "$id": "https://star-wars-codex-data/schema/work.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "additionalProperties": false,
  "properties": {
    "bookType": {
      "type": "string"
    },
    "canonStatus": {
      "enum": [
        "canon",
        "non-canon",
        "other"
      ],
      "type": "string"
    },
    "creators": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "name": {
            "minLength": 1,
            "type": "string"
          },
          "role": {
            "type": "string"
          },
          "slug": {
            "type": "string"
          }
        },
        "required": [
          "name"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "displayTitle": {
      "minLength": 1,
      "type": "string"
    },
    "editionIds": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "type": {
            "enum": [
              "isbn13",
              "isbn10",
              "asin",
              "audibleAsin",
              "upc",
              "diamondCode"
            ],
            "type": "string"
          },
          "value": {
            "type": "string"
          }
        },
        "required": [
          "type",
          "value"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "editions": {
      "items": {
        "additionalProperties": false,
        "properties": {
          "asin": {
            "type": "string"
          },
          "audibleAsin": {
            "type": "string"
          },
          "extent": {
            "type": "number"
          },
          "imprint": {
            "type": "string"
          },
          "isPrimary": {
            "type": "boolean"
          },
          "isbn10": {
            "type": "string"
          },
          "isbn13": {
            "type": "string"
          },
          "kind": {
            "enum": [
              "print",
              "ebook",
              "audio"
            ],
            "type": "string"
          },
          "onsale": {
            "type": "string"
          },
          "upc": {
            "type": "string"
          }
        },
        "required": [
          "kind"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "era": {
      "type": "string"
    },
    "format": {
      "type": "string"
    },
    "inUniverseDate": {
      "additionalProperties": false,
      "properties": {
        "endYear": {
          "type": "integer"
        },
        "startYear": {
          "type": "integer"
        }
      },
      "type": "object"
    },
    "movie": {
      "additionalProperties": false,
      "properties": {
        "movieType": {
          "type": "string"
        },
        "mpaaRating": {
          "type": "string"
        },
        "runtimeMinutes": {
          "type": "number"
        },
        "subtitle": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "parentWorkSlug": {
      "type": "string"
    },
    "periodical": {
      "additionalProperties": false,
      "properties": {
        "imprint": {
          "type": "string"
        },
        "pageCount": {
          "type": "number"
        },
        "publicationKind": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "type": "object"
    },
    "relatedWorkSlugs": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "releaseDate": {
      "type": "string"
    },
    "releaseDisplayState": {
      "type": "string"
    },
    "releaseStatus": {
      "type": "string"
    },
    "slug": {
      "minLength": 1,
      "type": "string"
    },
    "synopsis": {
      "type": "string"
    },
    "title": {
      "minLength": 1,
      "type": "string"
    }
  },
  "required": [
    "slug",
    "title",
    "displayTitle",
    "format",
    "canonStatus",
    "releaseDisplayState"
  ],
  "title": "Work",
  "type": "object"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/star-wars-insider-insider-158.json
{
  "canonStatus": "canon",
  "displayTitle": "Insider #158",
  "format": "periodicalIssue",
  "parentWorkSlug": "star-wars-insider",
  "periodical": {
    "publicationKind": "magazine"
  },
  "releaseDisplayState": "announced",
  "slug": "star-wars-insider-insider-158",
  "title": "Insider #158"
}

=== shawnphoffman/star-wars-codex-data/data/works/tv-season/the-clone-wars-season-2.json
{
  "canonStatus": "canon",
  "displayTitle": "The Clone Wars - Season 2",
  "format": "tvSeason",
  "inUniverseDate": {
    "endYear": -19,
    "startYear": -22
  },
  "parentWorkSlug": "the-clone-wars-series",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "the-clone-wars-season-2",
  "title": "The Clone Wars - Season 2"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/star-wars-insider-insider-43.json
{
  "canonStatus": "canon",
  "displayTitle": "Insider #43",
  "era": "multiEra",
  "format": "periodicalIssue",
  "parentWorkSlug": "star-wars-insider",
  "periodical": {
    "publicationKind": "magazine"
  },
  "releaseDate": "1999-04-01T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "star-wars-insider-insider-43",
  "synopsis": "Star Wars Insider 43 is the forty-third issue of Star Wars Insider magazine. It was published in April 1999. Three cover variants were available for issue 43: a newsstand version featuring Qui-Gon Jinn, a subscriber-exclusive version featuring Darth Maul, and a Previews Exclusive version similar to the subscriber version but with different coloring for the Star Wars Insider logo.",
  "title": "Insider #43"
}

=== shawnphoffman/star-wars-codex-data/data/works/book/boba-fett-crossfire.json
{
  "bookType": "juniorReader",
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "Terry Bisson",
      "role": "writer",
      "slug": "terry-bisson"
    }
  ],
  "displayTitle": "Boba Fett: Crossfire",
  "editionIds": [
    {
      "type": "isbn10",
      "value": "0439339286"
    },
    {
      "type": "isbn10",
      "value": "0439390028"
    },
    {
      "type": "isbn13",
      "value": "9780439339285"
    }
  ],
  "editions": [
    {
      "extent": 133,
      "imprint": "Scholastic",
      "isPrimary": false,
      "isbn10": "0439390028",
      "kind": "print",
      "onsale": "2002-11-01T00:00:00.000Z"
    },
    {
      "extent": 133,
      "imprint": "Scholastic",
      "isPrimary": true,
      "isbn10": "0439339286",
      "isbn13": "9780439339285",
      "kind": "print",
      "onsale": "2002-11-01T00:00:00.000Z"
    }
  ],
  "era": "reignOfTheEmpire",
  "format": "book",
  "inUniverseDate": {
    "startYear": -22
  },
  "releaseDate": "2002-11-01T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "boba-fett-crossfire",
  "synopsis": "On the planet Raxus Prime, young Boba Fett discovers Count Dooku may not be the person the future bounty hunter thought he was.",
  "title": "Boba Fett: Crossfire"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/tales-of-the-jedi-5-the-saga-of-nomi-sunrider-part-3.json
{
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "Tom Veitch",
      "role": "writer",
      "slug": "tom-veitch"
    }
  ],
  "displayTitle": "Tales of the Jedi #5: The Saga of Nomi Sunrider, Part 3",
  "era": "oldRepublic",
  "format": "periodicalIssue",
  "inUniverseDate": {
    "startYear": -3999
  },
  "parentWorkSlug": "tales-of-the-jedi-2",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "1994-02-01T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "tales-of-the-jedi-5-the-saga-of-nomi-sunrider-part-3",
  "synopsis": "Tales of the Jedi 5 is the fifth issue in the Tales of the Jedi series of comics. It was published on February 1, 1994 by Dark Horse Comics.",
  "title": "Tales of the Jedi #5: The Saga of Nomi Sunrider, Part 3"
}

=== shawnphoffman/star-wars-codex-data/data/works/book/the-high-republic-the-edge-of-balance-vol-1.json
{
  "bookType": "manga",
  "canonStatus": "canon",
  "creators": [
    {
      "name": "Shima Shinya",
      "role": "writer",
      "slug": "shima-shinya"
    },
    {
      "name": "Mizuki Sakakibara",
      "role": "artist",
      "slug": "mizuki-sakakibara"
    }
  ],
  "displayTitle": "The High Republic: The Edge Of Balance Vol. 1",
  "era": "highRepublic",
  "format": "book",
  "releaseDate": "2021-09-07T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "the-high-republic-the-edge-of-balance-vol-1",
  "synopsis": "In the aftermath of the Great Hyperspace Disaster, young Jedi Knight Lily Tora-Asi is assigned to help displaced civilians relocate to Banchii, a planet in the Inugg system far in the Outer Rim. While balancing the arrival of incoming settlers and teaching the Padawans on their Temple outpost, Lily must also confront an attack by the insidious Drengir and, after the events of the Republic Fair, deal with the growing threat of the Nihil. But the dangers to Lily and her Padawans are much closer than she thinks….",
  "title": "The High Republic: The Edge Of Balance Vol. 1"
}

=== shawnphoffman/star-wars-codex-data/data/works/video-game/super-star-wars-return-of-the-jedi.json
{
  "canonStatus": "non-canon",
  "displayTitle": "Super Star Wars: Return of the Jedi",
  "format": "videoGame",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "1994-01-01T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "super-star-wars-return-of-the-jedi",
  "synopsis": "Super Star Wars: Return of the Jedi, sometimes called Super Return of the Jedi, is a platform game for the Super Nintendo Entertainment System (Super Famicom in Japan) and Nintendo Game Boy which follows Super Star Wars and Super Star Wars: The Empire Strikes Back. There is also a simplified version for the Sega Game Gear portable system.",
  "title": "Super Star Wars: Return of the Jedi"
}

=== shawnphoffman/star-wars-codex-data/data/works/periodical-issue/star-wars-1977-star-wars-31-the-hunt-for-aurra-sing.json
{
  "canonStatus": "non-canon",
  "creators": [
    {
      "name": "Tim Truman",
      "role": "writer",
      "slug": "tim-truman"
    },
    {
      "name": "Davidé Fabbri",
      "role": "penciler",
      "slug": "david-fabbri"
    },
    {
      "name": "Christian Dalla Vecchia",
      "role": "inker",
      "slug": "christian-dalla-vecchia"
    },
    {
      "name": "David McCaig",
      "role": "colorist",
      "slug": "david-mccaig"
    },
    {
      "name": "Steve Dutro",
      "role": "letterer",
      "slug": "steve-dutro"
    },
    {
      "name": "Dave Land",
      "role": "editor",
      "slug": "dave-land"
    },
    {
      "name": "Darin Fabrick",
      "slug": "darin-fabrick"
    },
    {
      "name": "Jon Foster",
      "role": "coverArtist",
      "slug": "jon-foster"
    }
  ],
  "displayTitle": "Star Wars #31: The Hunt for Aurra Sing",
  "format": "periodicalIssue",
  "parentWorkSlug": "star-wars-1977",
  "periodical": {
    "publicationKind": "comic"
  },
  "releaseDate": "2001-06-27T00:00:00.000Z",
  "releaseDisplayState": "released",
  "releaseStatus": "released",
  "slug": "star-wars-1977-star-wars-31-the-hunt-for-aurra-sing",
  "synopsis": "On a dangerous jungle planet, the Dark Woman is shot and wounded while Aurra Sing seeks to kill her next mark -- the corrupt senator, Tikkes. The three Jedi who stand in her way, Adi Gallia, Ki-Adi-Mundi, and A'Sharad Hett, attempt to defend the remnants of the senator's suspicious Quarren expedition, rescue the Dark Woman, and bring Aurra Sing to justice before she carries out another assassination! Sing is pleased with this chance to add to her lightsaber collection while completing another deadly job! When confronted by Sing, will A'Sharad Hett succumb to his darkest desires and ultimately seek vengeance for the murder of his father? Will three Jedi be enough to take down this heartless warrior? \"The Hunt for Aurra Sing\" concludes with this exciting finale!",
  "title": "Star Wars #31: The Hunt for Aurra Sing"
}
